package com.sycw.sycw_check.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

@Getter @Setter
@ToString
public class Order {

  private String systemOrderNo;
  private String systemOrderType;
  private String ifKey;
  private String contactOrdNo;
  private String orderType;
  private String orderStatus;
  private String eta;
  private LocalDateTime etd;
  private LocalDateTime dueDate;
  private LocalDateTime orderReceiptDate;
  private LocalDateTime expPickupDate;
  private LocalDateTime appointmentDate;
  private String specialInstruction;
  private String apptConfirmedBy;
  private String invenOwnership;
  private String shippingDocNo;
  private double collectBillAmount;
  private String originalOrderNo;
  private String isUrgent;
  private String customerNo;
  private String destinationNo;
  private String address1;
  private String address2;
  private String address3;
  private String address4;
  private String province;
  private String telphon;
  private String fax;
  private String sms;
  private String email;
  private String city;
  private String zipCode;
  private String contactAreaCode;
  private String contactPerson;
  private String pickupNo;
  private String pickupName;
  private String pickupContactPerson;
  private String pickupAddr1;
  private String pickupAddr2;
  private String pickupAddr3;
  private String pickupAddr4;
  private String pickupContactAreaCode;
  private String pickupZipCode;
  private String pickupTel;
  private String pickupFax;
  private String pickupSmsNo;
  private String totItemQty;
  private String referenceNo;
  private String mchntOrderNo;
  private String inoutKbn;
  private String inoutNo;
  private String inoutNoSeq;
  private String shipType;
  private String vendorCd;
  private String docNo;
  private String funcCd;
  private String poNo;
  private String inoutEmpno;
  private String fromWhCd;
  private String toWhCd;
  private String outinplcCd;
  private String orgCd;
  private String teamCd;
  private String billNm;
  private String billAddr1;
  private String billAddr2;
  private String billCity;
  private String billState;
  private String billPostNo;
  private String reqDt;
  private String confDt;
  private String canReqDt;
  private String canDt;
  private String canUserId;
  private String canNonRsn;
  private String shipDesiredStart;
  private String shipDesiredEnd;
  private String shipArrivalDt;
  private String poolCd;
  private String digit4Type;
  private String digit5Dept;
  private String appointmentNo;
  private String payMethod;
  private String shipLoc;
  private String shipCarrier;
  private String shipMethod;
  private String trackNo;
  private String shipNm;
  private String shipEmail;
  private String shipPhone;
  private String shipAddr1;
  private String shipAddr2;
  private String shipCity;
  private String shipState;
  private String shipPostNo;
  private String taxType;
  private String receiptId;
  private String remark;
  private String procStscd;
  private String whShipCarrier;
  private String whShipMethod;
  private String whBlNo;
  private String whBlLink;
  private String tranStatus;
  private String recvDttm;
  private String confDttm;
  private String procDttm;
  private String updtDttm;
  private String applyStatus;
  private String inoutEmpnm;
  private String proNo;
  private String currency;
  private String status;
  private String apptNo;
  private String shipPallet;
  private String shipWeight;
  private String shipAmount;
  private String teamName;
  private String groupName;
  private String palletNo;
  private String scac;
  private String createUser;
  private LocalDateTime createDate;
  private String updateUser;
  private LocalDateTime updateDate;
  private String supplierNo;

}
